http://localhost:3030

###
http://localhost:3030/books

###
http://localhost:3030/books/1006

###
post http://localhost:3030/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlcmNoaWUiLCJpZCI6MSwiaWF0IjoxNjA0NDE2NjcyfQ.uISrLhwxo_tkNQxk7oXAiSYswvcdqtag3n-eym56e1U

{
  "title": "OOP In C#",
  "author": "Yaw Star",
  "number_of_pages": 230,
  "category": "programming",
  "rating": 7.5
}

###
post http://localhost:3030/admin/login
Content-Type: application/json

{
  "username": "berchie",
  "password": "mestapi20"
}

###
http://localhost:3030/authors/134